### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SanRob1325**

### CODE REVIEW

**Comment by SanRob1325** [comment]
New styling

**Comment by presleyigie1** [comment]
is that conflict still a problem or did you replace it with "new styling" push @SanRob1325

**Comment by SanRob1325** [comment]
Yeh,I'll think I'll just pull all the content when I'm done with the styling

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by SanRob1325** [comment]
> is that conflict still a problem or did you replace it with "new styling" push @SanRob1325

Yeh,it with the CSS, so I think I'll just add it as a last thing

**Pull request closed without merging**
